# Generated by Django 5.2.4 on 2025-08-12 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employeeprofile_domain_employeeprofile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='business_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_profiles', to='myapp.companyprofile'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
