# Generated by Django 5.2.4 on 2025-08-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_hrprofile_business_contact_number_hrprofile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
