# Generated by Django 5.2.4 on 2025-08-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='domain',
            field=models.CharField(choices=[('django', 'Django Developer'), ('web', 'Web Developer'), ('app', 'App Developer'), ('ml', 'Machine Learning'), ('data', 'Data Science'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
