# Generated by Django 5.2.4 on 2025-10-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_interviewquestion_interviewsession_interviewanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='final_score',
            field=models.FloatField(blank=True, help_text='Final session score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='rank',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
