# Generated by Django 5.2.4 on 2025-10-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_interviewsession_evaluated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='rank',
            field=models.CharField(blank=True, help_text='Human readable rank (Excellent/Good/...)', max_length=50, null=True),
        ),
    ]
